version: '3.9'
services:
  backend:
    image: baazigar018/torrent-downloader-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ${USER_DOWNLOADS}:/root/Downloads
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    image: baazigar018/torrent-downloader-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
